"""
generate_golden10_matlab.py
Project STREAMSENSE — Track A

Reads the existing golden_vectors/ binary files (generated by generate_golden.py)
and re-saves them in MATLAB-friendly column-major (Fortran) order into a new
folder:  C:\STREAMSENSE\golden_vectors_10_matlab\

The MATLAB team can then load every file with a plain reshape — no transpose trick.

Folder structure created:
    golden_vectors_10_matlab/
        raw/          GV_00_yes.bin          [16000]   float32  (unchanged — 1D has no layout issue)
        mel/          GV_00_yes_mel.bin      [64 x 97] float32  column-major
        normalized/   GV_00_yes_norm.bin     [64 x 97] float32  column-major
        labels/       GV_00_yes_label.txt    class index        (unchanged)
        README.txt    explains the layout to the MATLAB team
        manifest.json

MATLAB load (no tricks needed):
    fid  = fopen('GV_00_yes_norm.bin', 'rb', 'l');
    data = fread(fid, 64*97, 'float32=>single');
    fclose(fid);
    ref  = reshape(data, [64, 97]);   % correct — column-major matches file layout

Run from C:\\STREAMSENSE\\training\\ :
    python generate_golden10_matlab.py
"""

import numpy as np
import json
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT          = Path(r"C:\STREAMSENSE")
GV_SRC        = ROOT / "golden_vectors"          # existing Python golden vectors
GV_MATLAB     = ROOT / "golden_vectors_10_matlab" # new MATLAB-friendly folder
MANIFEST_SRC  = GV_SRC / "manifest.json"

# ── Output subdirectories ─────────────────────────────────────────────────────
RAW_OUT   = GV_MATLAB / "raw"
MEL_OUT   = GV_MATLAB / "mel"
NORM_OUT  = GV_MATLAB / "normalized"
LABEL_OUT = GV_MATLAB / "labels"

# ── Class labels ──────────────────────────────────────────────────────────────
LABELS = ['yes', 'no', 'up', 'down', 'left', 'right', 'on', 'off', 'stop', 'go']

# ── MPIC v1.0 frozen shapes ───────────────────────────────────────────────────
FRAME_LEN  = 16000
N_MELS     = 64
EXPECTED_T = 97


def load_rowmajor(path: Path, shape: tuple) -> np.ndarray:
    """Load a Python/NumPy row-major float32 binary file and reshape correctly."""
    data = np.fromfile(str(path), dtype=np.float32)
    if data.size != np.prod(shape):
        raise ValueError(f"Size mismatch in {path.name}: "
                         f"expected {np.prod(shape)} values, got {data.size}")
    return data.reshape(shape)   # C row-major — correct for Python-saved files


def save_colmajor(array: np.ndarray, path: Path):
    """Save array in Fortran column-major order (MATLAB-native layout).

    np.asfortranarray().tofile() is a known pitfall: tofile() always writes
    the C-contiguous view of the buffer, so it silently produces row-major
    bytes even for a Fortran array.  tobytes(order='F') forces the correct
    column-major byte sequence before writing.
    """
    path.write_bytes(array.tobytes(order="F"))


def write_readme(out_dir: Path):
    readme = out_dir / "README.txt"
    readme.write_text("""\
STREAMSENSE — Golden Vectors (MATLAB Edition)
=============================================
Generated by: generate_golden10_matlab.py
Layout:       Column-major (Fortran order) — MATLAB native

These files are re-saved versions of the standard golden_vectors/ binaries,
with 2D arrays (mel, normalized) stored in MATLAB column-major order so that
a plain reshape() call gives the correct [64 x 97] matrix.

File shapes:
  raw/        GV_0X_label.bin        [16000]   float32  little-endian
  mel/        GV_0X_label_mel.bin    [64 x 97] float32  little-endian  column-major
  normalized/ GV_0X_label_norm.bin   [64 x 97] float32  little-endian  column-major
  labels/     GV_0X_label_label.txt  plain text, class index 0-9

MATLAB load — copy-paste ready:
  % Raw audio (1D — no layout issue)
  fid = fopen('GV_00_yes.bin', 'rb', 'l');
  raw = fread(fid, 16000, 'float32=>single');
  fclose(fid);

  % Mel spectrogram [64 x 97]
  fid = fopen('GV_00_yes_mel.bin', 'rb', 'l');
  mel = reshape(fread(fid, 64*97, 'float32=>single'), [64, 97]);
  fclose(fid);

  % Normalised spectrogram [64 x 97]
  fid = fopen('GV_00_yes_norm.bin', 'rb', 'l');
  ref = reshape(fread(fid, 64*97, 'float32=>single'), [64, 97]);
  fclose(fid);

Tolerance: max(abs(streamsense_mel_pipeline(raw) - ref)) < 5e-4
""")


def main():
    print("=" * 60)
    print("STREAMSENSE — generate_golden10_matlab.py")
    print("=" * 60)
    print(f"Source : {GV_SRC}")
    print(f"Output : {GV_MATLAB}")

    # ── Validate source exists ────────────────────────────────────────────────
    for subdir in ["raw", "mel", "normalized", "labels"]:
        if not (GV_SRC / subdir).exists():
            print(f"[ERROR] Source folder not found: {GV_SRC / subdir}")
            print("        Run generate_golden.py first.")
            sys.exit(1)

    # ── Create output directories ─────────────────────────────────────────────
    for d in [RAW_OUT, MEL_OUT, NORM_OUT, LABEL_OUT]:
        d.mkdir(parents=True, exist_ok=True)

    write_readme(GV_MATLAB)

    manifest_out = {
        "description"  : "MATLAB-friendly golden vectors — column-major layout",
        "source"       : "generated by generate_golden10_matlab.py",
        "layout"       : "column-major Fortran order (MATLAB native)",
        "dtype"        : "float32",
        "endianness"   : "little",
        "matlab_reshape": "reshape(fread(fid,64*97,'float32=>single'),[64,97])",
        "vectors"      : {}
    }

    all_passed = True

    for i, lbl in enumerate(LABELS):
        gv_name = f"GV_{i:02d}_{lbl}"
        print(f"\n{'─'*50}")
        print(f"Processing {gv_name}  (class {i} — '{lbl}')")

        # ── Source file paths ─────────────────────────────────────────────────
        src_raw   = GV_SRC / "raw"        / f"{gv_name}.bin"
        src_mel   = GV_SRC / "mel"        / f"{gv_name}_mel.bin"
        src_norm  = GV_SRC / "normalized" / f"{gv_name}_norm.bin"
        src_label = GV_SRC / "labels"     / f"{gv_name}_label.txt"

        for p in [src_raw, src_mel, src_norm]:
            if not p.exists():
                print(f"  [ERROR] Missing: {p}")
                all_passed = False
                continue

        # ── Load Python row-major files ───────────────────────────────────────
        raw  = load_rowmajor(src_raw,  (FRAME_LEN,))          # [16000]
        mel  = load_rowmajor(src_mel,  (N_MELS, EXPECTED_T))  # [64, 97]
        norm = load_rowmajor(src_norm, (N_MELS, EXPECTED_T))  # [64, 97]

        # ── Output file paths ─────────────────────────────────────────────────
        dst_raw   = RAW_OUT   / f"{gv_name}.bin"
        dst_mel   = MEL_OUT   / f"{gv_name}_mel.bin"
        dst_norm  = NORM_OUT  / f"{gv_name}_norm.bin"
        dst_label = LABEL_OUT / f"{gv_name}_label.txt"

        # ── Save raw (1D — no layout change needed) ───────────────────────────
        raw.tofile(str(dst_raw))

        # ── Save mel and norm in MATLAB column-major order ────────────────────
        save_colmajor(mel,  dst_mel)
        save_colmajor(norm, dst_norm)

        # ── Copy label file ───────────────────────────────────────────────────
        if src_label.exists():
            dst_label.write_text(src_label.read_text())
        else:
            dst_label.write_text(str(i))

        # ── Validate output sizes ─────────────────────────────────────────────
        expected_raw_bytes  = FRAME_LEN * 4             # 64000
        expected_mel_bytes  = N_MELS * EXPECTED_T * 4  # 24832  (64 * 97 * 4)

        ok_raw  = dst_raw.stat().st_size  == expected_raw_bytes
        ok_mel  = dst_mel.stat().st_size  == expected_mel_bytes
        ok_norm = dst_norm.stat().st_size == expected_mel_bytes

        if not (ok_raw and ok_mel and ok_norm):
            all_passed = False

        print(f"  raw  → {dst_raw.name}   {dst_raw.stat().st_size} bytes  {'OK' if ok_raw else 'FAIL'}")
        print(f"  mel  → {dst_mel.name}  {dst_mel.stat().st_size} bytes  {'OK' if ok_mel else 'FAIL'}")
        print(f"  norm → {dst_norm.name}  {dst_norm.stat().st_size} bytes  {'OK' if ok_norm else 'FAIL'}")

        # ── Self-verify: reload and compare to original ───────────────────────
        # The file holds column-major bytes (col varies slowest).
        # np.fromfile reads them flat; reshape with order='F' fills column-by-column,
        # which is the inverse of tobytes(order='F'), so norm_rebuilt == norm exactly.
        norm_reloaded = np.fromfile(str(dst_norm), dtype=np.float32)
        norm_rebuilt  = norm_reloaded.reshape((N_MELS, EXPECTED_T), order='F')
        max_err = float(np.max(np.abs(norm_rebuilt - norm)))
        print(f"  self-check max_err = {max_err:.2e}  {'OK' if max_err < 1e-7 else 'FAIL'}")

        manifest_out["vectors"][str(i)] = {
            "gv_name"   : gv_name,
            "class_idx" : i,
            "label"     : lbl,
            "raw_file"  : dst_raw.name,
            "mel_file"  : dst_mel.name,
            "norm_file" : dst_norm.name,
            "raw_shape" : [FRAME_LEN],
            "mel_shape" : [N_MELS, EXPECTED_T],
            "norm_shape": [N_MELS, EXPECTED_T],
            "norm_mean" : round(float(norm.mean()), 6),
            "norm_std"  : round(float(norm.std()),  6),
            "size_ok"   : ok_raw and ok_mel and ok_norm,
        }

    # ── Write manifest ────────────────────────────────────────────────────────
    manifest_path = GV_MATLAB / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest_out, f, indent=2)

    # ── Final summary ─────────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    for i, lbl in enumerate(LABELS):
        v = manifest_out["vectors"].get(str(i), {})
        status = "PASS" if v.get("size_ok") else "FAIL"
        print(f"  [{status}] GV_{i:02d}_{lbl}")

    print(f"\nManifest  → {manifest_path}")
    print(f"README    → {GV_MATLAB / 'README.txt'}")

    if all_passed:
        print(f"\n[DONE] golden_vectors_10_matlab/ is ready to share.")
        print(f"       Share the entire folder: {GV_MATLAB}")
        print(f"       MATLAB team uses plain reshape — no transpose needed.")
    else:
        print("\n[FAIL] Some vectors failed — check errors above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
